### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by atechdad** [rapid7/dap#1]
Is there any documentation for the tool outside of the examples?

**Comment by jhart-r7** [comment]
@atechdad, sorry for the delay.

Aside from [the samples](https://github.com/rapid7/dap/tree/master/samples), unfortunately the only thing close to documentation is the code itself.  

If you have specific questions about if dap does something or how to do something with dap, feel free to ask in a separate issue.  Alternatively, we welcome PRs to add documentation :smile:
