### ISSUE TITLE
decode sonar ssl

### ISSUE THREAD

**Issue by s3c1t** [rapid7/dap#10]
i downloaded 
https://scans.io/data/rapid7/sonar.ssl/20160509/20160509_certs.gz
https://scans.io/data/rapid7/sonar.ssl/20160509/20160509_hosts.gz
https://scans.io/data/rapid7/sonar.ssl/20160509/20160509_names.gz
from scans.io
i readed 20160509/20160509_hosts.gz similar following
zcat 20160509/20160509_hosts.gz |less . but there is unclear strings. 
for example:
13.90.214.57,38113203d606e5f5459575d9687e5d849ba7b799
13.90.214.57,948e1652586240d453287ab69caeb8f2f4f02117
23.0.17.189,6ad2b04e2196e48bf685752890e811cd2ed60606
...
i hex decoded some strings. and again got unclear string
now this is my question: how decode or decrypt mentioned unclear string

**Comment by hdm** [comment]
This repository is for DAP development, please direct these questions to the community web site in the future: https://community.rapid7.com/

The ``hosts`` output is the IP address followed by a hash of the X509 certificate. To figure out what certificate is on what host, grab *all* of the cert files, and search them for the hash you are looking for (they are incremental). The ``certs`` file is keyed by the hash and contains a base64 encoded copy of the raw X509 certificate.

**Comment by jhart-r7** [comment]
Thanks @hdm.  @s3c1t, in addition to the community link posted by HD, if you have further questions, you can email research[at]rapid7.com.
