### ISSUE TITLE
Splitting Subdomains?

### ISSUE THREAD

**Issue by Manouchehri** [rapid7/dap#38]
End up resorting to awk today, but it'd be nice if I could do everything in dap.

Input:

```json
{  
   "value":"cloud.appspider.rapid7.com"
}
```

Desired output:

```json
{  
   "value":"cloud.appspider.rapid7.com",
   "value.f1":"cloud",
   "value.f2":"appspider",
   "value.f3":"rapid7",
   "value.f4":"com"
}
```

**Comment by jhart-r7** [comment]
@Manouchehri thanks for the ticket -- I've released `dap` 0.1.6 that has this functionality.
