### ISSUE TITLE
Error installing dap on MAC

### ISSUE THREAD

**Issue by versatilepisces** [rapid7/dap#76]
Building native extensions.  This could take a while...
ERROR:  Error installing dap:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/geoip-c-0.9.1/ext/geoip
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20190916-24561-1oci3x7.rb extconf.rb
checking for iconv_open() in iconv.h... no
checking for iconv_open() in -liconv... yes
checking for GeoIP_record_by_ipnum() in -lGeoIP... no
you must have geoip c library installed!
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
	--with-geoip-dir
	--without-geoip-dir
	--with-geoip-include
	--without-geoip-include=${geoip-dir}/include
	--with-geoip-lib
	--without-geoip-lib=${geoip-dir}/lib
	--with-iconvlib
	--without-iconvlib
	--with-GeoIPlib
	--without-GeoIPlib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/geoip-c-0.9.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/geoip-c-0.9.1 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/geoip-c-0.9.1/gem_make.out

**Comment by tsellers-r7** [comment]
Sorry we missed your message here @versatilepisces 

The issue can be corrected by running `brew install geoip` to install the missing dependency for the `geoip-c` Ruby gem.  I've incidentally run into this myself today and have updated the macos installation documentation via PR #78

**Comment by perryBunn** [comment]
The brew install doesn't work for Chromebooks (probably because its not installed by default) but manually installing [geoip-api-c](https://github.com/maxmind/geoip-api-c#installation) fixed it for me.
